name: CI/CD Pipeline - Docker Deployment

on:
  push:
    branches:
      - 'release/**'

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Docker Container
        run: |
          # 1. Construir la nueva imagen de Docker
           docker build -t arkue-frontend .
          
          # 2. Detener y eliminar la versión anterior (ignorando errores si no existe)
           docker stop arkue-frontend-container || true
           docker rm arkue-frontend-container || true
          
          # 3. Desplegar el nuevo contenedor mapeando el puerto 80
           docker run -d --name arkue-frontend-container -p 80:80 arkue-frontend
